clone_folder: c:\projects\tori

os:
  - Visual Studio 2017
  - Visual Studio 2017 Preview

platform: 
  - x64

configuration:
  - Debug
  - Release

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - cmake --build .

test_script:
- ctest -V -C Debug