# enable trusty
dist: trusty
sudo: required
# c++
language: cpp
# new stuff is good stuff
# test on clang and gcc

matrix:
  include:
    # linux g++7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: 
        - MATRIX_EVAL="COMPILER=g++-7"

    # linux g++8
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: 
        - MATRIX_EVAL="COMPILER=g++-8"
    
    # linux clang 6.0
    - os: linux
      before_install:
        - sudo apt-get update
        - sudo apt-get purge g++
        - sudo apt-get install g++-7
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 1000
        - sudo apt-get install clang-6.0
        - COMPILER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    # linux clang 7.0
    - os: linux
      before_install:
        - sudo apt-get update
        - sudo apt-get purge g++
        - sudo apt-get install g++-8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 1000
        - sudo apt-get install clang-7.0
        - COMPILER=clang++-7.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7.0

before_install:
  - eval "${MATRIX_EVAL}"

# lets go
script:
  - $COMPILER --version
  - mkdir build
  - cd build 
  - cmake .. -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build .
  - ctest -V